name = input("Who are you?")
city = input('Where do you live?')
age = input ('How old are you')
hobby = input('What is your hobby')
movie = input ("What is your Favourite movie")
food = input("What is your favorite food?")

print ("------YOUR DETAILS FILLED BY YOU-------")
print ("Name:",name)
print ('City:',city)
print("Age:",age)
print("Hobby:",hobby)
print ("Movie:",movie)
print("Food:",food)
print("-----THE END-----")